### PR TITLE
Changes to support 3006.102.1 F/W

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Made a change to comply with JS file dependencies on the 3006.102.1 F/W builds.
This fixes errors when loading the WebGUI page.

### CODE REVIEW

**Comment by Martinski4GitHub** [comment]
@juched78.

Please let me know if you have any questions or concerns regarding the changes in this PR.

Take care, mate!!

**Comment by ExtremeFiretop** [comment]
Just wanted to mention I just installed the WebUI for unbound on 3006 firmware and noticed it didn't load correctly:

image

I also noticed this PR was merged in the dev branch and it doesn't seem to be in sync with the main branch, any chances theres steps to enable updates to the dev branch? Or that dev may get merged to master soon?

If not; I can manually copy the changes for now.

**Comment by ExtremeFiretop** [comment]
@Martinski4GitHub and @juched78 

Actually I just went ahead and did it, and all is well with the dev version:

image

**Comment by juched78** [comment]
Yes. Sorry I no longer have any Asus routers.  This branch is not seeing any activity.    I can merge but cannot validate.

**Comment by ExtremeFiretop** [comment]
> Yes. Sorry I no longer have any Asus routers. This branch is not seeing any activity. I can merge but cannot validate.

Understood and that is unfortunate; in that case please take my tests and screenshots above as validation that this PR is good to merge to production/master branch :)

**Comment by Martinski4GitHub** [comment]
> Yes. Sorry I no longer have any Asus routers. This branch is not seeing any activity. I can merge but cannot validate.
>
>
I also know of at least 3 users who have been running the WebUI with the fix included in this PR for about 4-5 months, and they have validated that it works fine on **3006.102.x.y**, **3004.386.x.y** & **3004.388.x.y** F/W builds.

Just FYI.

**Comment by juched78** [comment]
So sorry it took so long.  I had read the email and then it got buried and I forgot.  I have given Martinski collaborator access.  This can move to AMTM Orphaned Scripts if so desired.

**Comment by Martinski4GitHub** [comment]
> So sorry it took so long. I had read the email and then it got buried and I forgot. I have given Martinski collaborator access. This can move to AMTM Orphaned Scripts if so desired.
>
>
I understand, no worries. Things happen. It's all good now.
Thank you for the collaborator access.

**Pull request merged**
